### ISSUE TITLE
jets deploy fails

### ISSUE THREAD

**Issue by grandpa78** [tongueroo/jets#132]
Deploy fails with
`=> Copying current project directory to temporary build area: /tmp/jets/demo/stage/code
Traceback (most recent call last):
        15: from /usr/local/bundle/bin/jets:23:in `<main>'
        14: from /usr/local/bundle/bin/jets:23:in `load'
        13: from /usr/local/bundle/gems/jets-1.4.9/exe/jets:14:in `<top (required)>'
        12: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/cli.rb:5:in `start'
        11: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/cli.rb:21:in `start'
        10: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/commands/base.rb:27:in `perform'
         9: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/commands/base.rb:38:in `dispatch'
         8: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         7: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         6: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         5: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/commands/main.rb:21:in `deploy'
         4: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/commands/deploy.rb:29:in `run'
         3: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/commands/deploy.rb:49:in `build_code'
         2: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/commands/build.rb:27:in `build_code'
         1: from /usr/local/bundle/gems/jets-1.4.9/lib/jets/builders/code_builder.rb:38:in `build'
/usr/local/bundle/gems/jets-1.4.9/lib/jets/builders/code_builder.rb:38:in `chdir': No such file or directory @ dir_chdir - /tmp/jets/demo/stage/code (Errno::ENOENT)`

**Comment by grandpa78** [comment]
Closed ?

**Comment by tongueroo** [comment]
Please read the requirements for posting issues 👌 Thanks!
