### ISSUE TITLE
Change S3 Deployment Bucket?

### ISSUE THREAD

**Issue by mdwagner** [tongueroo/jets#145]
How do I change the S3 deployment bucket from the default? I can't find it anywhere in the config for this...

**Comment by tongueroo** [comment]
This is currently not possible. Jets generates and manages this s3 bucket. Unsure if there's a good enough use case for this tbh.

**Comment by tongueroo** [comment]
Also, please use https://community.rubyonjets.com/ for questions 👌  Thanks!

**Comment by mdwagner** [comment]
@tongueroo Well our use case it we're looking to add Jets for our app and we only have some certain buckets approved by our DevOps that we can use for deploying.

**Comment by tongueroo** [comment]
I see. Thanks for providing the use case! Happy to consider PRs. Thanks!
