### ISSUE TITLE
Ensure Bundler Available on AWS Lambda: Bundle error After deploy

### ISSUE THREAD

**Issue by efreesen** [tongueroo/jets#151]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    MacOS X 10.13.6     |
| Jets             |     1.5.6    |
| Ruby             |    2.5.3     |

---

## Expected Behaviour

After deploy the API should work properly and respond accordingly.

## Current Behavior

The lambda function returns the following error:

`cannot load such file -- bundler/setup`

With the following stacktrace

```
Init error when loading handler handlers/controllers/api_controller.index
{
  "errorMessage": "cannot load such file -- bundler/setup",
  "errorType": "Init<LoadError>",
  "stackTrace": [
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
    "/var/task/handlers/controllers/api_controller.rb:1:in `<top (required)>'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
  ]
}
START RequestId: 3e6be219-1bef-40ae-b948-9e8b3831a03b Version: $LATEST
```

## Step-by-step reproduction instructions

Clone the following [project](https://github.com/efreesen/jets-bundler-bug), deploy it to AWS Lambda and try to access the `/api` endpoint.

## Code Sample

https://github.com/efreesen/jets-bundler-bug

## Solution Suggestion

It seems the app cannot find the bundler gem, I tried to add the bundler into the zip but it didn't work.

The solution I see is to pack the bundler with the other dependencies if this is really the problem.

**Comment by tongueroo** [comment]
Thanks for the example project. Noticed that the bundler version you are using is 1.17.2.  Looks like I'm on version 2.0.1

```diff
-   2.0.1
+   1.17.2
```

Wondering if you can give updating a shot:

```
gem install bundler
bundle update # to update Gemfile.lock in the project
```

**Comment by efreesen** [comment]
Thank you for the amazing job with this framework!

Updated the project with the correct bundler version.

Yup, maybe if you add support for `2.6.0` this problem is gone as bundler is integrated. 😃

**Comment by wontruefree** [comment]
I am still having problems with this :(

**Comment by tongueroo** [comment]
@wontruefree Yup. Think this is related https://discuss.circleci.com/t/bundler-2-0-was-released-and-bundler-may-not-be-happy/27521

Unsure why it was working even yesterday but fix is in #155 Testing it out now.

**Comment by tongueroo** [comment]
Released in v1.5.8 [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)

**Comment by wontruefree** [comment]
@tongueroo I found out there was a local cache causing problems.  When I cleared the cache it worked.

**Comment by tongueroo** [comment]
Oh I see. Good to know. Thanks for posting for others.  Think the latest release will also help also.
