### ISSUE TITLE
Add `rescue_from` functionality to Jets controllers

### ISSUE THREAD

**Issue by CodingAnarchy** [tongueroo/jets#207]
## Summary

A version of `ActiveSupport::Rescuable` for Jets controllers/functions.

## Motivation

This feature would allow for familiar Rails-style exception handling, particularly in use cases like custom authentication layers (in `before_action` filters) or external API calls using libraries like `RestClient`. 

## Guide-level explanation

The idea is to support a `rescue_from` block/method assignment as in a Rails controller, so that the following syntax would be possible:

```ruby
class ExampleController < Jets::Controller::Base
    rescue_from ActiveRecord::RecordNotFound do |exception|
       # custom exception handling code
    end

    rescue_from StandardError, with: :custom_exception_handler
end
```

## Reference-level explanation

Rails implements this behavior as a concern, via `ActiveSupport::Concern` libraries: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/rescuable.rb

Implementation by including ActiveSupport might be the simplest route, but not necessarily the best for the goals of the Jets framework, so I am open to alternative options.  (Presently, I _believe_ I can achieve this result - at least locally - by including ActiveSupport as a gem and manually including the `ActiveSupport::Rescuable` concern, but this is obviously inferior to having it be part of the framework itself. I also have not definitively verified that this is the case.)

## Drawbacks

The simplest way to do this would be to include a version of ActiveSupport as a dependency for Jets. (I am assuming that nothing about deploying to AWS Lambda would prevent the `ActiveSupport::Concern` framework from working as it does in a Rails application.). This might, however, be a bit too weighty for the Jets framework, so implementing this feature may involve taking just part of the code for ActiveSupport and adapting it to Jets.

## Unresolved Questions

Whether including any other aspects of `ActiveSupport` would be beneficial to the Jets framework.

**Comment by tongueroo** [comment]
Think using ActiveSupport to add rescue_from is fine.

**Comment by tongueroo** [comment]
@CodingAnarchy Thanks for the #211 PR!
