### ISSUE TITLE
Support MFA STS

### ISSUE THREAD

**Issue by rberger** [tongueroo/jets#213]
## Summary

We now require MFA for all Infrastructure access. It would be very helpful if Jets supported MFA. Everyone should be using MFA for everything. Especially their core infrastructure.

## Motivation

Companies have literally been destroyed because members of a team were not using
2FA:
_[AWS console breach leads to demise of service with “proven” backup plan](http://arstechnica.com/security/2014/06/aws-console-breach-leads-to-demise-of-service-with-proven-backup-plan/)_

![Bad Password Management, No 2FA](https://cdn.arstechnica.net/wp-content/uploads/2014/06/oops-640x480.jpg)

That was for a console breach, but the CLI is potentially even bigger security hole. 

If you are not using MFA for everything, particularly for your root infrastructure, you will eventually have something very unpleasant happen.

## Guide-level explanation

1. Make GET-SESSION-TOKEN API call. The output of this API call is credentials which are MFA authenticated credentials. 
2. Now use these returned credentials to perform all API calls  including assume-role. In this case you dont need MFA parameters to be passed because returned creds already have MFA creds

https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html

## Reference-level explanation

* The Ruby  AWS SDK of interest: 
  * https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/STS/Client.html 
  *  Search for MFA
* There is a gist that shows an example:  
  * https://gist.github.com/brandonrich/67c0ae24b5abfef65134
* AWS CLI equivalent: 
  * https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html

## Drawbacks

It increases dev friction a bit, but its really nice not to have your company go out of business when your laptop is stolen.

## Unresolved Questions

Support for Assumed Roles from within Jets. Should be able to have set it up externally by setting the AWS_PROFILE

**Comment by gaurish** [comment]
For people looking to use MFA enabled accounts wit Jets, they can use https://github.com/remind101/assume-role to export ENV vars like `AWS_ACCESS_KEY_ID`, `AWS_SESSION_TOKEN` etc in the same shell shell before running Jets. 

it will work just fine.

**Comment by tongueroo** [comment]
> RE: Picture in issue

😂

> RE: MFA Support

Done in #402

Dug into this. For posterity, here are a few useful links:

* https://github.com/broamski/aws-mfa
* https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/
* https://github.com/lonelyplanet/aws-mfa

Didn't work the way was hoping for.  Created a gem to handle: https://github.com/tongueroo/aws-mfa-secure  

Eventually, when the aws cli and ruby sdk officially supports MFA for a standard IAM user, can get rid of aws-mfa-secure.
