### ISSUE TITLE
Why is it in test mode while running in CircleCI ?

### ISSUE THREAD

**Issue by pocari** [tongueroo/jets#218]
I deployed from circleci. But `region` and `aws account` was not correct in generated lambda role.

So, I checked `aws_info.rb`, I found following code.
https://github.com/tongueroo/jets/blob/4fd2d2c190594e29b9581c3f62a8685ff277ef78/lib/jets/aws_info.rb#L90

Is there any reason for this?

I am currently doing something like 
```
unset CIRCLECI
jets deploy
```
to get around this in circleci build.

**Comment by tongueroo** [comment]
Dont remember the exactly reason anymore. Maybe it was just a safeguard I put in place when initially setting up circleci for jets. Anyway, removed in #219 and will go out in the next release. 

Glad you found a workaround though.
