### ISSUE TITLE
Invalid key for dead letter queue in application config

### ISSUE THREAD

**Issue by bartblast** [tongueroo/jets#221]
## My Environment

macOS Mojave 10.14.3
Jets 1.8.9
Ruby 2.5.3p105

## Expected Behaviour

I'm able to specify dead letter queue ARN in the application config.

## Current Behavior

Deploy rolls back, because CloudFormation detects invalid property when using a config entry similar to this:
config.function.dead_letter_queue = { target_arn: "arn:aws:sqs:us-east-1:123:abc" }

## Step-by-step reproduction instructions

Set config.function.dead_letter_queue = { target_arn: ... } to some valid SQS ARN and try to deploy.

## Solution Suggestion

Use config.function.dead_letter_config instead of config.function.dead_letter_queue works correctly.

It seems that you only need to update the generate application config file to fix it.

**Comment by tongueroo** [comment]
Done in #222
