### ISSUE TITLE
Jets 1.8.9 install failure on Windows

### ISSUE THREAD

**Issue by Donavan** [tongueroo/jets#226]
- [N/A ] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ N/A] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  Windows 10       |
| Jets             |   1.8.9      |
| Ruby             |  2.5.3p105       |

---

## Expected Behaviour

Gem installs corectly

## Current Behavior

Gem does not install

## Step-by-step reproduction instructions

Execute 'gem install jets"

Receive error message: 

ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path vendor/rails/actionpack/test/fixtures/公共/bar/index.html of C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jets-1.8.9 is not allowed

## Code Sample

N/A

## Solution Suggestion

I was able to get around it by pulling the jets repo, removing the folder fixtures/公共/ and rebuilding the gem.

**Comment by tongueroo** [comment]
Not counting it out for the future, but don't think will support Windows for now. 😕
