### ISSUE TITLE
undefined method `red' when deploying

### ISSUE THREAD

**Issue by dbackeus** [tongueroo/jets#229]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   MacOS Mojave 10.14.4      |
| Jets             |   1.8.9      |
| Ruby             |    2.5.3     |

---

## Expected Behaviour

When running `jets deploy` it should give me a helpful error message if the deploy fails for whatever reason.

I believe it actually worked the first time I ran it on this system but all subsequent times have had the same issues. Even when generating new apps from scratch.

## Current Behavior

When running `jets deploy` after S3 bucket has been created and populated I get the following stack trace:
```
Traceback (most recent call last):
	16: from /Users/davidbackeus/.rbenv/versions/2.5.3/bin/jets:23:in `<main>'
	15: from /Users/davidbackeus/.rbenv/versions/2.5.3/bin/jets:23:in `load'
	14: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/exe/jets:14:in `<top (required)>'
	13: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/cli.rb:5:in `start'
	12: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/cli.rb:21:in `start'
	11: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/commands/base.rb:27:in `perform'
	10: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/commands/base.rb:38:in `dispatch'
	 9: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 8: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 7: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 6: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/commands/main.rb:21:in `deploy'
	 5: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/commands/deploy.rb:34:in `run'
	 4: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/commands/deploy.rb:81:in `ship'
	 3: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/cfn/ship.rb:20:in `run'
	 2: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/cfn/ship.rb:54:in `save_stack'
	 1: from /Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/cfn/ship.rb:65:in `update_stack'
/Users/davidbackeus/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jets-1.8.9/lib/jets/cfn/ship.rb:69:in `rescue in update_stack': undefined method `red' for #<String:0x00000001130eed18> (NoMethodError)
```

Looking at the stack on Cloudfront it has only created the S3 bucket on the Cloudformation stack. No gateway API or lambda functions etc.

## Step-by-step reproduction instructions

```
jets new <app-name> --database=postgresql
cd <app-name>
echo "2.5.3" > .ruby-version
jets deploy
```

## Solution Suggestion

This should be changed to `.color(:red)`: https://github.com/tongueroo/jets/blob/master/lib/jets/cfn/ship.rb#L69

**Comment by dbackeus** [comment]
Fixed the error in PR #230. After running `jets deploy` using my fixed branch I can verify that the actual deploy error reported by AWS was:

```
ERROR: Template format error: Unrecognized resource types: [AWS::Lambda::LayerVersion]
```

Possibly `LayerVersion` isn't supported in the `eu-north-1` region. Haven't found any official documentation on the topic but there is a forum post echoing the same issue: https://forums.aws.amazon.com/thread.jspa?messageID=892152

**Comment by tongueroo** [comment]
> RE: undefined method .red

Thanks for the fix! 

> RE: Possibly LayerVersion isn't supported in the eu-north-1 region.

Yup, some regions don't fully support Lambda yet. Another user also ran into this on the community forums: [Unrecognized resource types: [AWS::Lambda::LayerVersion]](https://community.rubyonjets.com/t/unrecognized-resource-types-aws-layerversion/115/3)

This [AWS Region Table Matrix](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/) helps. 

> RE: It would be nice if jets would validate that the current region is supported and fail early with a nice error message instead of ending up with a half broken deploy and a cryptic error.

Think so too. Though hesitant to add a check and then when AWS adds support to a region, we'll have to maintain that table. Thinking docs would be a better approach.  Point the user to the docs as a helpful tip.  Will take PRs for this.

Anyway, thanks for the fix!

**Comment by dbackeus** [comment]
Had a look at the matrix. Not sure what to look for to determine `LayerVersion` support though? According to the matrix "Lambda" is supported in all regions. We're having a lab week at my company and I might be spending the whole week labbing with Jets so I might get time to improve your docs if I know what to look for :)
