### ISSUE TITLE
Broken link on "API Gateway Routes" docs

### ISSUE THREAD

**Issue by iamrahulroy** [tongueroo/jets#236]
## Motivation

> Jets translates config/routes.rb definitions to API Gateway Resources: Routing Overview. 

The link to "Routing Overview" is currently broken. The link is pointing here http://rubyonjets.com/docs/routing-overview/ 

## Suggestion

The link should point here http://rubyonjets.com/docs/routing/

If there's no PR related to the issue, then I can go ahead and submit a PR. Thanks.

**Comment by tongueroo** [comment]
@iamrahulroy Yes, please feel free to fix broken links.

**Comment by iamrahulroy** [comment]
@tongueroo Cool! I'll go ahead and submit a PR by EOD(IST). Thanks!
