### ISSUE TITLE
Update documentation with support for rake tasks

### ISSUE THREAD

**Issue by iamrahulroy** [tongueroo/jets#241]
## Motivation

I couldn't find a way to include rake tasks for jets application in the documentation. 

Rails support adding rake files inside `lib/tasks` folder.

[Rake supports `rakelib` out of the box.](https://github.com/ruby/rake/blob/master/doc/rakefile.rdoc#multiple-rake-files)

## Suggestion

We should update the documentation with the suggestion of adding `rakelib` directory to include rake tasks.

Let me know, where does this piece of information belong in the jets documentation.

- [Project Structure](http://rubyonjets.com/docs/structure/)
- Under Extras? 
- Someplace else?

Let me know, I'll go ahead and submit a PR.

## Alternate Solution

Support for `lib/tasks` directory. I can submit a PR for this too, but I will need your guidance.

**Comment by sonxurxo** [comment]
I also missed a `rake tasks` section in the docs.
I went in the way of the alternate solution by loading all tasks in `lib/tasks` by adding this line to the Rakefile:
```
Dir.glob('lib/tasks/*.rake').each { |r| load r}
```
This way, all tasks in that folder are automatically available.

**Comment by tongueroo** [comment]
Done #318 Released in [v2.0.0](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md) 🎉

@sonxurxo Thanks for the code snippet.
