### ISSUE TITLE
Why is it so slow in local development mode ?

### ISSUE THREAD

**Issue by sofianegargouri** [tongueroo/jets#253]
Hi guys !

I've been using Jets as an API for a few weeks now, but I can't understand why it is really slow in development mode while being fast once deployed on Lambda.
I'm not talking about 1s slow, but more like a 10 seconds interval between the beginning of a simple request and its answer.

Thanks a lot !

**Comment by tongueroo** [comment]
Related to https://github.com/tongueroo/jets/issues/240 Currently using shotgun to handle reloading. And it’s slow 😔 Will look into https://github.com/fxn/zeitwerk

Have heard of some folks using https://github.com/dblock/guard-rack as workaround for now. There’s a little downtime during rack restarting but at least it’s faster. 

Am looking forward to a faster reloader though. Will close this out in favor of #240
