### ISSUE TITLE
Endpoint request timed out 

### ISSUE THREAD

**Issue by chebyte** [tongueroo/jets#279]
Hello there I followed this tutorial 

https://blog.boltops.com/2018/09/08/jets-tutorial-deploy-to-aws-lambda-part-2

I can access to the root url but when I try to access to

 https://xxxxxx-api.us-east-2.amazonaws.com/dev/posts

it returns 

  "message": "Endpoint request timed out"

any idea?

**Comment by tongueroo** [comment]
Let's move questions to https://community.rubyonjets.com/ Thanks! 👍
