### ISSUE TITLE
Reloading all folders inside app

### ISSUE THREAD

**Issue by sofianegargouri** [tongueroo/jets#280]
## Summary

- Enable reloading of all files inside `app`

## Motivation

Actually, I have a projet with Pundit policies, ActiveModelSerializer serializers and custom services, inside folders named `app/policies`, `app/serializers` and `app/services`.
Those files aren't reloaded when updated, which forces me to restart my Jets server each time

## Guide-level explanation

/

## Reference-level explanation

/

## Drawbacks

If it loses a lot of perfs I guess, but I supposed it won't.

## Unresolved Questions

Maybe exclude folders like `app/javascripts` or `app/assets` ?

**Comment by tongueroo** [comment]
Interesting, am not seeing the this issue. Here's a repo with an example. Here's how it was tested:

Start server:

    jets server

Curl the posts endpoint:

    curl localhost:8888/posts

Change files:

* [app/serializers/post_serializer.rb](app/serializers/post_serializer.rb)
* [app/services/post_service.rb](app/services/post_service.rb)

Curl the posts endpoint again and see the changes:

    curl localhost:8888/posts

## Example

Before:

    $ curl localhost:8888/posts ; echo
    {"serialize":{"title":"test1editanother"},"service":"list3"}
    $

After some changes:

    $ curl localhost:8888/posts ; echo
    {"serialize":{"title":"test1editanother","body":null},"service":"list1"}
    $

Wondering why it's happening in your case. Also, when you get a chance can you fill out the "Reproducible Bug Report" GitHub issue template.  Unsure what versions you're running.

**Comment by tongueroo** [comment]
Thinking this fixed in #283 Released in [v1.9.11](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md) 🎉  Reopen if it's not.
