### ISSUE TITLE
How to start jobs from models ?

### ISSUE THREAD

**Issue by sofianegargouri** [tongueroo/jets#291]
Hey !

Is there any way to trigger jobs other than crons ? I'm trying to call a job from a model, but absolutely nothing happens.

The job:

```
# frozen_string_literal: true

class AssetSenderJob < ApplicationJob
  def run
    resource_type = event['resource_type']
    resource_id = event['resource_id']

    p resource_type
    p resource_id
  end
end
```

And it gets called from a model:

```
# frozen_string_literal: true

require 'aasm'

module ActsAsAsset
    def __schedule_sending_to_mux!
      return if Jets.env.test? || Jets.env.cucumber?

      event = {
        resource_type: model_name.name,
        resource_id: id
      }

      if Jets.env.development?
        AssetSenderJob.perform_now :run, event
      else
        AssetSenderJob.perform_later :run, event
      end
    end
  end
end
```

Can't make neither `perform_now` nor `perform_later` to work on Lambda. `perform_now` does work on development

**Comment by tongueroo** [comment]
@sofianegargouri Let's move questions to https://community.rubyonjets.com/ 👍

Though, this likely has to do with IAM permissions. Remotely on AWS Lambda, the functions need to have the IAM permission to call lambda.  The iam_policy needs to be added to the function that actually gets executed. Or you can add an application-wide configuration.  More docs:

* https://rubyonjets.com/docs/iam-policies/
* https://blog.boltops.com/2018/09/11/jets-tutorial-iam-policies-part-5

Function-specific iam policy:

```ruby
class HardJob < ApplicationJob
  include ActsAsAsset
  iam_policy "lambda"
  def dig
     _schedule_sending_to_mux! # leads to AssetSenderJob.perform_* methods
  end
end
```

Or application-wide iam policy:

```ruby
Jets.application.configure do |config|
  config.iam_policy = [
    Jets::Application.default_iam_policy, 
    "lambda"
  ]
end
```
