### ISSUE TITLE
Generated form with datetime doesn't produce valid field

### ISSUE THREAD

**Issue by keoghpe** [tongueroo/jets#294]
## Checklist

- [x ] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    MacOS     |
| Jets             |    1.9.18     |
| Ruby             |     2.6.3    |

---

## Expected Behaviour

Generating a resource with a datetime should generate a form with the appropriate datetime field.

## Current Behavior

Jets generates a form with `datetime_select_tag` resulting in a action view undefined method error.

```
ActionView::Template::Error: undefined method `datetime_select_tag' for #<#<Class:0x00007ff4faac6038>:0x00007ff4fd951c40>
Did you mean?  datetime_select
               datetime_field_tag
```

## Step-by-step reproduction instructions

Generate a resource with a `datetime`:

`jets g resource MyResource my_time:datetime`

Visit `localhost:8888/my_resources/new`

## Solution Suggestion

Update the generator to produce `datetime_field_tag`. I initially tried to use `datetime_select` but this didn't save to the DB.

**Comment by tongueroo** [comment]
Done #318 Released in [v2.0.0](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md) 🎉
