### ISSUE TITLE
`Jets.once` sometime stuck with “Init<Seahorse::Client::NetworkingError>” error on AWS lambda

### ISSUE THREAD

**Issue by krishnarama12** [tongueroo/jets#297]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   AWS Lambda      |
| Jets             |    1.9.9     |
| Ruby             |    2.5.0     |

---

## Expected Behaviour
Lambda Function should return simple string

## Current Behavior
```
{
“errorMessage”: “execution expired”,
“errorType”: “InitSeahorse::Client::NetworkingError”,
“stackTrace”: [
“/var/lang/lib/ruby/2.5.0/net/http.rb:937:in initialize'", "/var/lang/lib/ruby/2.5.0/net/http.rb:937:inopen’”,
“/var/lang/lib/ruby/2.5.0/net/http.rb:937:in block in connect'", "/var/lang/lib/ruby/2.5.0/timeout.rb:103:intimeout’”,
“/var/lang/lib/ruby/2.5.0/net/http.rb:935:in connect'", "/var/lang/lib/ruby/2.5.0/net/http.rb:920:indo_start’”,
“/var/lang/lib/ruby/2.5.0/net/http.rb:915:in start'", "/var/lang/lib/ruby/2.5.0/delegate.rb:83:inmethod_missing’”,
“/opt/ruby/gems/2.5.0/gems/aws-sdk-core-3.54.1/lib/seahorse/client/net_http/connection_pool.rb:297:in 
...
```

## Step-by-step reproduction instructions
Jets deploy the project with lambda gateway code given in code sample. Also put AWS Lambda function  inside VPC with privileges (subnets etc...) to access public internet.
The error happens intermittently so sometime function will work fine and sometime it fails. 

<details>
 <summary>`Jets.once` sometime stuck with “Init<Seahorse::Client::NetworkingError>” error on AWS lambda </summary>
 ...Simple Ruby/Jets AWS lambda function which is running under VPC with all the privileges to access public internet, sometime fails to execute with “InitSeahorse::Client::NetworkingError” . The function do not have any code except to return simple string...
</details>

## Code Sample
```
require "bundler/setup"
require "jets"
Jets.once  # runs once in lambda execution context
def index(event:, context:)
    return "Success"
end
```

**Comment by tongueroo** [comment]
Handled in #298 Released in [v1.9.20](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
