### ISSUE TITLE
Add support to test response headers

### ISSUE THREAD

**Issue by nathanpalmer** [tongueroo/jets#309]
## Summary

I'm looking at converting a very simple rails app that returns image responses. I want to test that the response `content_type` is correct. However, it seems the `response` object

## Motivation

Having a level of comfort that when changes get rolled out that we didn't accidentally change the content_type.

## Guide-level explanation

If you need to test response headers you can access the `headers` hash as part of the `response` object like this.

```ruby
response.headers['Content-Type'].to eq('image/png')
```

## Drawbacks

None that I can think of.

**Comment by tongueroo** [comment]
Done in #331 Released in [v2.0.3](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)

**Comment by nathanpalmer** [comment]
Thanks!
