### ISSUE TITLE
The function does work after deployed.

### ISSUE THREAD

**Issue by Yu-coding** [tongueroo/jets#314]
Hi @tongueroo 
Thanks for your great work.

I have deployed rails app on aws lambda using `jets deploy` command.
It worked on locally but after deployed without any issues it does work and when I call the function, it shows this error message.
```
{
    "message": "Internal server error"
}
```

I have checked Cloudwatch logs and I found this log.

```
18:19:39
RubyError: Errno::EAFNOSUPPORT: Failed to open TCP connection to localhost:9292 (Address family not supported by protocol - socket(2) for "localhost" port 9292)
RubyError: Errno::EAFNOSUPPORT: Failed to open TCP connection to localhost:9292 (Address family not supported by protocol - socket(2) for "localhost" port 9292)

18:19:39
/var/lang/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'

Could you please fix this issue for me?
Thank you.
/var/lang/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
```

**Comment by Yu-coding** [comment]
I am using the latest `Jets` version.

**Comment by Yu-coding** [comment]
I saw your work on `https://github.com/tongueroo/jets/pull/247`.
But on my side, it does show.

**Comment by galetahub** [comment]
Hi,

It seems your rails app are trying to connect to the localhost:9292 via TCP. Of course, you are getting the error because lambda function cannot access localhost. 

What service are you using at 9292 port? 
I think you have to change your env variables for deployment

**Comment by Yu-coding** [comment]
Hi @galetahub 
Thanks for reaching me.

Here, localhost:9292 means 9292 port on AWS which Jets provide as a default.
Am I sth wrong?

**Comment by Yu-coding** [comment]
Anyway, I have fixed this issue.
The original issue was -
`/opt/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)`

I have moved the `uglifier` and `coffee-rails` gems in the development group.
This helped me. :)

**Comment by galetahub** [comment]
Ah, now I see.
