### ISSUE TITLE
Deploy environment with different name

### ISSUE THREAD

**Issue by ChrisBr** [tongueroo/jets#321]
## Summary
We would like to deploy several staging environments with different names, e.g. for each Pull Request we would like to deploy staging Lambda.

## Motivation
Something like Heroku does with Review Apps:
> Review apps run the code in any GitHub pull request in a complete, disposable Heroku app. Review apps each have a unique URL you can share, making them a great way to propose, test, and merge changes to your code base.

https://devcenter.heroku.com/articles/github-integration-review-apps

Maybe there is even already a way to do this?

**Comment by tongueroo** [comment]
What a cool and interesting concept. I see how heroku is able to achieve this. They have a server-side git hook. You `git push` to a heroku managed repo. Heroku can evaluate the `app.json` and deploy upon a PR being created using the server side git hook. 

Jets does not have access to a server-side git hook. So this feature wouldn’t be a part of Jets. 

Think this could be achieved with Jets ENV_EXTRA and CI though. Related links:

* https://rubyonjets.com/docs/env-extra/
* https://rubyonjets.com/docs/extras/codebuild
* https://codebuild.cloud/docs/examples/jets/

Hope that helps.  👍

**Comment by ChrisBr** [comment]
> Think this could be achieved with Jets ENV_EXTRA and CI though. Related links:

That's actually what I was looking for 👍 Thanks for the links!
