### ISSUE TITLE
Add CI for Jets Pull Requests

### ISSUE THREAD

**Issue by jacobherrington** [tongueroo/jets#323]
I might be mistaken, but it seems like there is not CI running on Pull Requests, is that something we can configure? Most CI providers have a free or cheap tier for Open Source. Do you have thoughts on this @tongueroo?

**Comment by ChrisBr** [comment]
Seems like there is already a Circle CI config, wondering if we could enable PR integration?

**Comment by tongueroo** [comment]
Took a quick look at this today. Need to remove some scripts from the CI process first. Will dig into this further. Unsure when though.

**Comment by tongueroo** [comment]
Enabled builds on PRs from forks.
