### ISSUE TITLE
gem install jets not working without postgresql installed locally

### ISSUE THREAD

**Issue by stefangomez** [tongueroo/jets#33]
looks like I needed to have postgresql installed locally on my mac (High Sierra 10.13.6 w/Xcode 9.4.1 w/devtools installed) in order to install the jets gem. should probably note this (and other possible dependencies) in the installation docs. I see this note in your gemspec, but having this in the quick start could be helpful until this req is removed :)

https://github.com/tongueroo/jets/blob/master/jets.gemspec#L53

This issue is about <http://rubyonjets.com/docs/install/> (source file: <https://github.com/tongueroo/jets/blob/master/docs/_docs/install.md>)

**Comment by tongueroo** [comment]
Thanks for the bug report 👍 Fixed in PR #35 

Also added a `--no-database` option that tells `jets new` to not insert the `pg` gem to the generated Gemfile.

Released in v0.8.15 https://github.com/tongueroo/jets/blob/master/CHANGELOG.md
