### ISSUE TITLE
Support for "apiKeyRequired" option for API method

### ISSUE THREAD

**Issue by galetahub** [tongueroo/jets#334]
## Summary

AWS Gateway API has API keys mechanism. But jets does not have the option "Require API Key on a Method"

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-setup-api-key-with-console.html

## Motivation

I want to protect my API methods from others. Only clients with API keys can access it.
It's the easiest way to control/manage API clients

## Guide-level explanation

I think we can add option api_key_required: true|false, same as authorization_type here https://github.com/tongueroo/jets/blob/fdef815c5e108bff210bfe2e0c7bcb434101f5fd/lib/jets/resource/api_gateway/method.rb

Option api_key_required can have different levels, such as global, controller and route. In the same way that authorization_type does

**Comment by tongueroo** [comment]
Released in [v2.0.5](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
