### ISSUE TITLE
'resources' for api mode generates wrong routes

### ISSUE THREAD

**Issue by stefangomez** [tongueroo/jets#34]
looks like specifically for api-mode /new and /edit routes need to be taken out 

https://github.com/tongueroo/jets/blob/163f51ff3c1dbb5ec486bd2f5ed90711e64e680b/lib/jets/router.rb#L22

**Comment by tongueroo** [comment]
Thanks for the bug report. Fixed in PR #36 

The new and edit methods are no longer included as part of the `resources` macro. Example:

    $ jets routes
    +--------+-----------+--------------------+
    |  Verb  |   Path    | Controller#action  |
    +--------+-----------+--------------------+
    | GET    | posts     | posts#index        |
    | GET    | posts/:id | posts#show         |
    | POST   | posts     | posts#create       |
    | PUT    | posts/:id | posts#update       |
    | DELETE | posts/:id | posts#delete       |
    | GET    |           | jets/welcome#index |
    | ANY    | *catchall | jets/public#show   |
    +--------+-----------+--------------------+
    $

Released in v0.8.15 https://github.com/tongueroo/jets/blob/master/CHANGELOG.md
