### ISSUE TITLE
Support ApiGateway Lambda Authorizer

### ISSUE THREAD

**Issue by galetahub** [tongueroo/jets#361]
## Summary

Authorizers enable you to control access to your APIs using Amazon Cognito User Pools or a Lambda function. More info https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

## Motivation

Jets has already ```authorization_type = :custom``` and I think the next step is to allow developers to define an authorizer and a lambda function for it (if the authorizer type is Lambda).

## Guide-level explanation

When authorizer is a lambda function:
1. Define some lambda function to be used for authorizer:
```
class RequestsController < ApplicationController
  def create
   ...
  end
end
```
2. Define the authorizer and link to the lambda function:
```
Jets.application.routes.draw do
  authorizer :somename, to: "requets#create", type: 'token', ttl: 300
end
```

3. Add authorizer to your private route (controller):
```
Jets.application.routes.draw do
  authorizer :somename, to: "requets#create", type: 'token', ttl: 300

  get  "posts", to: "posts#index", authorization_type: :custom, authorizer: :somename
end
```

Thanks!

**Comment by tongueroo** [comment]
Done in #368  Interface is slightly different. Details in there.

**Comment by galetahub** [comment]
Thanks!
