### ISSUE TITLE
Minimal IAM Policies

### ISSUE THREAD

**Issue by y8** [tongueroo/jets#37]
Hey!

I'm having trouble configuring permissions for to perform a deploy to AWS. Can you add list of permissions required in the docs? 

Thanks!

**Comment by tongueroo** [comment]
* Docs: http://rubyonjets.com/docs/minimal-deploy-iam/
* Done in #38 
* Released in v0.8.16: [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
