### ISSUE TITLE
Would like details about Amazon Aurora Serverless

### ISSUE THREAD

**Issue by cayblood** [tongueroo/jets#371]
This issue is about <http://rubyonjets.com/docs/database/activerecord/> (source file: <https://github.com/tongueroo/jets/blob/master/docs/_docs/database/activerecord.md>)

It would be nice if this page mentioned whether or not Amazon Aurora Serverless is supported. Seems like this would be a nice option, although there may be some challenge I'm not aware of that would make it difficult.

**Comment by tongueroo** [comment]
Should be supporters since Aurora is MySQL compatible. Some folks on the community board mentioned it so believe they are using it.  Can add a note or take a PR.
