### ISSUE TITLE
templateBody failed to satisfy constraint: Member must have length less than or equal to 51200

### ISSUE THREAD

**Issue by galetahub** [tongueroo/jets#379]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | Linux |
| Jets                       | 2.3.0 |
| Ruby                     | 2.5.5|

---

## Expected Behaviour

Successfully deploy the project to AWS without any limitation errors

## Current Behavior

AWS Template body size in a request is limited to 51,200 bytes
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200

## Step-by-step reproduction instructions

Create a lot of routes with namespace and controllers for if.

## Code Sample

```ruby
Jets.application.routes.draw do
  namespace :api do
    namespace :v1 do
      namespace :feedbacks do
        resources :messages, only: [:index, :create]
      end
     
     # More then 100 lines of other routes
  end
end
```

## Solution Suggestion

The most better solution is to upload the template file to s3. AWS says that the limit will be 460,800 bytes in this case. Then replace "template-body" with "template-url" when deploying stack to AWS 

Thanks!

**Comment by tongueroo** [comment]
Done in #384 Thanks!
