### ISSUE TITLE
Should this be dev, not rev?

### ISSUE THREAD

**Issue by wr0ngway** [tongueroo/jets#380]
https://github.com/tongueroo/jets/blame/112d9ff4f91c4dafc160d63371f15aaaafe0ec89/docs/_docs/extras/minimal-deploy-iam.md#L111

I'm having some permission problems with the minimal IAM permissions - rev seems like it could be a typo for dev in the Lambda permissions section, which is correct?

**Comment by tongueroo** [comment]
Yup. Thanks!
