### ISSUE TITLE
Remove unnecessary things for an API based application

### ISSUE THREAD

**Issue by twistapp** [tongueroo/jets#390]
Hi,

I would like to know what things I can remove if I just want to build a API. I've ran `jets new api --mode api` to generate a new API and I see what appears to be things I don't need within the `public` directory. May I remove the entire `public` directory, or shouldn't I?

Thanks.

**Comment by tongueroo** [comment]
Let’s put questions on the [community forums](https://community.rubyonjets.com/) 👍

You can remove the public folder just fine though. Be sure to update the default route also. 

Think the ‘jets new -mode api’ can updated to do this also. Will dig into in time.

**Comment by twistapp** [comment]
@tongueroo awesome! Thank you for the awesome framework and sorry for posting the question here.
