### ISSUE TITLE
Feature Request: Trigger lambda function based on s3 or sqs event

### ISSUE THREAD

**Issue by onnimonni** [tongueroo/jets#41]
I really enjoy how https://github.com/aws/chalice contains a nice way to trigger events based on sqs or s3 event like this:

```python
from chalice import Chalice

app = Chalice(app_name="helloworld")

# Whenver an object is uploaded to 'mybucket'
# this lambda function will be invoked.

@app.on_s3_event(bucket='mybucket')
def handler(event):
    print("Object uploaded for bucket: %s, key: %s"
          % (event.bucket, event.key))
```

We could have something similiar in Jets.

I'm not sure if you already have something in mind to implement background job queues.

I'm thinking of using Jets to replace some of my data processing pipelines. 
An example use case:
1. Cloudwatch scheduled background job fetches file through sftp and saves it to s3
2. Second lambda is triggered when there's a new file in the s3 bucket. It will parse the file and save the results to RDS.
3. If the file had any errors, schedule an sqs event for another lambda which emails the error to given recipients.

This way the max execution time (5min) will be enough for almost any input.

And of course I don't want to overwhelm you with too many requests and I can try to implement this myself a bit later.

**Comment by tongueroo** [comment]
Completely make sense. This a very good use-case. Been thinking about similar things 👍  Yes, want this also be added. Cheers if you or someone else gets to it before me 🎉

**Comment by pocheptsov** [comment]
Unrelated to this issue, so we can start a separate conversation, @tongueroo have you thought about abstracting AWS Lambda implementation, so it could potentially support other cloud providers or even be cross-cloud?

**Comment by tongueroo** [comment]
@pocheptsov Great question 👍  Addressed in #43

**Comment by tongueroo** [comment]
@onnimonni s3 and sqs support added 👍 Docs:

* http://rubyonjets.com/docs/events-s3/ as of v1.8.0
* http://rubyonjets.com/docs/events-sqs/ as of v1.7.0

**Comment by onnimonni** [comment]
Cool! Thanks for these 🍻
