### ISSUE TITLE
Copied "Lambda Console Link" doesn't honour the selected region.

### ISSUE THREAD

**Issue by gokaykucuk** [tongueroo/jets#416]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | OSX 10.15.2 |
| Jets             | 2.3.8 |
| Ruby             | 2.5.3 |

---

## Expected Behaviour

I have AWS-CLI installed, and my accounts region is configured to eu-central-1.

When I run 
``` bundle exec jets call setup_job-create_tables```
It prints "Pro tip: The Lambda Console Link to the project-dev-setup_job-create_tables function has been added to your clipboard.".

The copied link should be as follows,
```
https://console.aws.amazon.com/lambda/home\?region\=eu-central-1\#/functions/project-dev-setup_job-create_tables\?tab\=configuration
```

## Current Behavior

The copied link is as follows,
```
https://console.aws.amazon.com/lambda/home\?region\=us-east-1\#/functions/project-dev-setup_job-create_tables\?tab\=configuration
```

## Step-by-step reproduction instructions

- Create a job.
- Try calling the job from terminal with "jets call"
- Paste the copied url into a textbox.

## Solution Suggestion

I have not enough information to suggest a solution at the moment as I haven't checked what Jets is doing to generate the URL. But my wild guess is it's not asking AWS-CLI for the region information.

**Comment by gokaykucuk** [comment]
Digging a bit more showed me that when i run,
```
> aws configure get region
eu-central-1
```
But when i try to debug ```jets/commands/call.rb:138```, 

```
> Aws.config
{}
```
So Aws.config is not loaded when the call is made, I'll try to dig a bit more and come up with a PR if i can find a good soln.

**Comment by gokaykucuk** [comment]
Also found a possible soln,
```
https://github.com/aws/aws-sdk-ruby/issues/1042
```
Will try to come up with a PR soon.

**Comment by tongueroo** [comment]
Thanks. Could be related to #415 also
