### ISSUE TITLE
"INFO: No internet connection available. Only local services are currently available"

### ISSUE THREAD

**Issue by MilesRomney** [tongueroo/jets#420]
Running Ubuntu 18.04 (under the Windows Linux Subsystem). My Jets application (api) generated properly. But when trying to run "jets console" or "jets db:create", it hangs for about 3 minutes then shows this error:

INFO: No internet connection available. Only local services are currently available

There is indeed an internet connection, verified via curl.

**Comment by tongueroo** [comment]
Unsure. Need more info. Please fill out issue template.

**Comment by MilesRomney** [comment]
- [x ] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System | Ubuntu 18.04 under WLS  |
| Jets             | 2.3.10 |
| Ruby             | 2.5.0 |

---

## Expected Behaviour

Running "jets console" should quickly load the Jets console.

Running "jets db:create" should ~quickly create a database.

## Current Behavior

After ~3 minutes, this message appears:

> INFO: No internet connection available. Only local services are currently available

Running "curl https://google.com" verifies that an internet connection is available. (And I had just barely run "bundle install" and successfully installed all gems over the internet connection.)

**Comment by MilesRomney** [comment]
I've just installed Jets on a fresh AWS EC2 VM with Ubuntu 18.04. After installing Jets, I installed the AWS CLI, and wrote .env and config/database.yml files. And I ran "aws configure" and added my credentials.

When I run "jets console" or "jets db:create", I'm getting the same error I'm seeing locally. (Though on the VM, I get it within ~10 seconds rather than ~3 minutes.)

I have confirmed that the AWS credentials are good. (It's a highly privileged IAM account, for the sake of proving out the connection without the possibility of permissions problems.)

**Comment by MilesRomney** [comment]
It does appear to be related to configuring the AWS CLI, though. If I remove ~/.aws/credentials and run the Jets commands, I get a warning about missing AWS credentials, but the commands run successfully locally.

Adding ~/.aws/credentials back brings the "No internet connection available" error back.

**Comment by MilesRomney** [comment]
![image](https://user-images.githubusercontent.com/48551/71607528-5fe10700-2b37-11ea-89a2-f2077d6e9972.png)

Spelling error in the default region name when configuring AWS CLI. 🤦‍♂ When I ran a CLI command like `aws s3 ls` I got a connection error as well.

You can close this out.
