### ISSUE TITLE
Make jets deploy --noop command print CloudFormation template

### ISSUE THREAD

**Issue by prashcr** [tongueroo/jets#442]
## Summary

When I run
```
jets deploy --noop
```
I expect to see the CloudFormation template created for the Jets app printed to a file or STDOUT

## Motivation

This feature exists in [cody](https://github.com/tongueroo/cody/).
* It's useful to review templates before deployment to ensure there are no unexpected surprises
* It's quicker to check the template first to confirm if the DSL I wrote does what I want, instead of running `jets deploy` and waiting at least 90 seconds for the Cloudformation stack to update then looking up the resource in AWS console/CLI to confirm.

## Guide-level explanation

To view the CloudFormation template generated by Jets
```
jets deploy --noop
```

## Reference-level explanation

When the `--noop` flag is passed to `deploy`, print out the CloudFormation template to `/tmp/jets.yml`

**Comment by tongueroo** [comment]
Sure. FWIW, there’s also a “jets build” for now. But a noop option is good too.

**Comment by prashcr** [comment]
Good to know! I'll raise a PR to print the location of the CloudFormation template when `jets build --templates` is run, that should suffice. I noticed it gets printed to `/tmp/jets/<app-name>/templates/*.yml`
