### ISSUE TITLE
Add Job helper methods for DynamoDB events

### ISSUE THREAD

**Issue by prashcr** [tongueroo/jets#450]
## Motivation

When DynamoDB events are configured for a Job, there are no helper methods that make it easier to access the contents of the event.

Similar to `LogEventHelper`/`KinesisEventHelper`/`S3EventHelper`, it would be nice to have a `DynamoDBEventHelper` that provides methods to access the DynamoDB objects

## Guide-level explanation

For functions triggered by DynamoDB events, you can use `dynamodb_keys`, `dynamodb_new_images` or `dynamodb_old_images` to access those attributes on the StreamRecords.

```
def MinerJob
  dynamodb_event 'gold_mine'
  def dig
    puts dynamodb_new_images
  end
end

<= output =>
[
  {
    "id" => "f565ff19-6565-4044-a806-5b2cf447b0fc",
    "color" => "green"
  },
  {
    "id" => "5546ec41-5660-4b78-bdc0-779e787e7e6c",
    "temperature" => 25.5
  }
]
```

## Reference-level explanation

It would involve adding a file like this:

```
module Jets::Job::Helpers
  module DynamoDBEventHelper
    def dynamodb_new_images
      records = event["Records"]
      records.map do |record|
        encoded = record["dynamodb"]["NewImage"]
        # TODO: parse records to remove type defs
      end
    end
    ...
  end
end
```

**Comment by tongueroo** [comment]
Feel like “dynamodb_new_images” is a little too business logic specific, at least that’s my current thoughts on it.
