### ISSUE TITLE
Getting Over the Lambda size limit of 250MB

### ISSUE THREAD

**Issue by hamza-sondermarketing** [tongueroo/jets#460]
I have added a rails application to the jets application using Jets Afterburner mode(https://rubyonjets.com/docs/rails/afterburner/)

when I try to deploy the application using the command jets deploy, it is giving me the error below.
Over the Lambda size limit of 250MB Please reduce the size of your code. Sizes: Code: 0.6MB - /tmp/jets/sonder-hcm/stage/code Gem Layer: 279.5MB - /tmp/jets/sonder-hcm/stage/opt Total Package: 280.1MB Over limit by: 30.1MB Sometimes blowing away the /tmp/jets cache will reduce the size: rm -rf /tmp/jets

Can some one please advise what to do in order to get this error fix and deploy successfully ?

**Comment by tongueroo** [comment]
Please refer to the issues guidelines https://github.com/tongueroo/jets/issues/new/choose Thanks

**Comment by KaitakuShiba** [comment]
In my case, after Delopoy, I noticed that Lambda was using Ruby 2.6, and I switched to 2.7 in the middle of the process, but the gem of the two versions had been packaged in duplicate, so I was overloaded.
So I removed the package under vender and re-installed it.
