### ISSUE TITLE
demo-rails app -> Endpoint request timed out

### ISSUE THREAD

**Issue by hamza-sondermarketing** [tongueroo/jets#464]
## Checklist
- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   UBUNTU 18.04      |
| Jets             | 2.3.15  |
| Ruby             |  2.5.3 |

---

## Expected Behaviour
I have followed [jets-afterburner-serverless-rails-on-aws-lambda-in-5-minutes](https://blog.boltops.com/2018/12/21/jets-afterburner-serverless-rails-on-aws-lambda-in-5-minutes) and try to deploy the demo rails application with `jets deploy` command.
Every thing seems to work as I don't get any error in the cloudwatch logs but upon hitting the endpoint returned from the after deploy command, it should load the demo rails site.

## Current Behavior
After hitting the Endpoint `https://lo4lne31h5.execute-api.us-east-1.amazonaws.com/dev/`, instead of loading the content, it displays the following message:

> {
> message: "Endpoint request timed out"
> }

## CloudWatch Logs

![cloudwatch1](https://user-images.githubusercontent.com/61772563/78118074-e4d20a00-741f-11ea-9036-291a3c1b5338.png)

## Code Sample
I have used the existing [demo-rails](https://github.com/tongueroo/demo-railsl) repo in my project and code can be found here: [my-rails-demo-app](https://github.com/hamza-sondermarketing/demo-rails-lambda)

## Solution Suggestion
I have shared the logs above and found no issues, but still it is timeout. No idea whats going on here. Kindly suggest.

**Comment by hamza-sondermarketing** [comment]
@tongueroo This is kind of an urgent issue that needs to be fix. Can you help me out here. I have checked and verified my DATABASE_URL on local and it is connecting and working fine.
I really don't understand where the issue is as cloudwatch is not telling me any issue.

**Comment by tongueroo** [comment]
@hamza-sondermarketing This is not urgent. It's a demo app. 

This is more of a usage question. Please review the issue guidelines again. Like these other issues: #456 #460 #463 Keeping questions on the forum helps keep the signal-to-noise ratio higher.

Responded to the community post with some tips: https://community.rubyonjets.com/t/could-not-find-a-javascript-runtime-see-https-github-com-rails-execjs-for-a-list-of-available-runtimes-execjs-runtimeunavailable/440
