### ISSUE TITLE
jets build fails

### ISSUE THREAD

**Issue by matiaskorhonen** [tongueroo/jets#66]
Running `jets build` fails for me with the following error message:

```
Requested resource not found
Error evaluating ERB template on line 7 of: /Users/matt/.rvm/gems/ruby-2.5.1/gems/jets-1.0.4/lib/jets/builders/templates/handler.js
2
3 const shim = require("handlers/shim.js");
4
5 shim.once(); // runs in lambda execution context
6
7 <% @vars.functions.each do |function_name| %>
8 exports.<%= function_name %> = shim.handler("<%= @vars.handler_for(function_name) %>");
9 <% end -%>
```

**Comment by tongueroo** [comment]
@matiaskorhonen Interesting, it's erroring generating the shim handler. Something with `@vars.functions`

If possible, can you post the app code that it's trying to generate? 

Also, can you add a `puts "variables: #{variables}"` at the top fo the `def result` method in `jets/erb.rb`?  And run `jets build` again. So something like this:

```ruby
  class << self
    def result(path, variables={})
      puts "variables: #{variables}" # add this line
      set_template_variables(variables)
```

You can usually find the `jets/erb.rb` file like this:

```
cd your-jets-project
ls $(bundle show jets)/lib/jets/erb.rb
```

Hoping the output of `jets build` will provide some more clues. Let me know.

Also, notice the version of jets being used is `jets-1.0.4` . It's probably good to upgrade to the latest version. Been making fixes and changes.

**Comment by matiaskorhonen** [comment]
Updating Jets seems to have solved my issue
