### ISSUE TITLE
Exception reporting

### ISSUE THREAD

**Issue by matiaskorhonen** [tongueroo/jets#70]
I'd like to add exception reporting (probably [Sentry](https://sentry.io), possibly [Honeybadger](https://www.honeybadger.io/)) to my Jets app.

What's the best way of getting the reporting to work without having to rescue the exceptions manually?

**Comment by tongueroo** [comment]
@matiaskorhonen Great question.  Right now you have to do it manually as there's no application-wide exception handling hook yet. Will dig into adding this. 🧐

**Comment by tongueroo** [comment]
@matiaskorhonen Added exception reporting support. Add and configure one of these gems to your Jets project. Refer to each readme to for the env var to configure.

* https://github.com/tongueroo/sentry-jets
* https://github.com/tongueroo/rollbar-jets
* https://github.com/tongueroo/honeybadger-jets 

As a part of this, introduced a new concept called a [Turbine](http://rubyonjets.com/docs/jets-turbines/). Essentially a Railtie.  Thinking this will ultimately a way hook into Jets and add plugin support, etc. Will take some time to figure a proper interface, but started the interface and released it to support this use case.

Released in v1.0.17 [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)

**Comment by matiaskorhonen** [comment]
Thanks for the awesomely quick response!
