### ISSUE TITLE
Integrate the AWS Lambda official support of Ruby 

### ISSUE THREAD

**Issue by nsanta** [tongueroo/jets#83]
Due to the recents announcements of AWS bringing official support for AWS lambda, Jets should be adapted.

More info here:
https://aws.amazon.com/blogs/compute/announcing-ruby-support-for-aws-lambda/

**Comment by tongueroo** [comment]
Yup. Already starting digging through the docs. Excited to get Jets on the official version of Ruby.

**Comment by tongueroo** [comment]
Jets is now on the AWS official Ruby Support. 🎉  Here's also a blog post covering it: https://blog.boltops.com/2018/12/12/official-aws-ruby-support-for-jets-serverless-framework

**Comment by nsanta** [comment]
Congratulations @tongueroo
