### ISSUE TITLE
Feature Request: consistent CLI for jets scripts

### ISSUE THREAD

**Issue by thepry** [tongueroo/jets#95]
Would be nice if CLI interface was consistent. Right now you can `jets deploy production`, but can't `jets delete production`. Instead I had to use `JETS_ENV=production jets delete`.

**Comment by tongueroo** [comment]
Addressed in #97 

## Test

    $ jets delete production
    Please report a bug if this causes problems.
    Deleting project...
    Are you sure you want to want to delete the demo-prod project? (y/N)
    ...

**Comment by tongueroo** [comment]
Released in v1.3.6 [CHANGELOG](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md)
